### PR TITLE
Add IFB interface to limit container egress (host ingress) bandwidth

### PR DESCRIPTION
**Pull request by sykesm**
Bandwidth limiting of container egress (host ingress) requires an intermediate functional block device to properly shape the network flow. Without this pattern, packets leaving the container are dropped instead
of getting throttled. This packet loss causes very poor overall throughput of application responses.

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
@fraenkel Do you have any feedback on this PR? Don't know much about Warden and network shaping, was hoping to get a review before the dev team pulls it in.  Related PRs are in:

* DEA: https://github.com/cloudfoundry/dea_ng/pull/177
* cf-release: https://github.com/cloudfoundry/cf-release/pull/836

**Comment by fraenkel** [comment]
These are good to go. Should have had Matt comment on the fact that I was next to him when he did all this. He spent most of his time just getting the traffic shaping to work properly for both inbound and outbound which is why it's different than what was originally there.

**Comment by sykesm** [comment]
@Amit-PivotalLabs you could have asked me to explain and I would have been happy to elaborate.

**Comment by sykesm** [comment]
Linux, in general, can't directly perform traffic shaping on ingress data; it only lets you specify a policing policy that drops packets when a limit is exceeded. When packets are dropped, the data rate is kept below the limit but it behaves like a lossy network link. This is different from egress behavior where traffic shaping can buffer and delay packets instead of simply dropping them.

The current warden implementation uses the ingress policing policy to drop packets when the bandwidth exceeds the specified limit. What we found in our experiments was that the with a limit of 1MB/s, downloads into the container (host egress / container ingress) behaved very well but uploads out of the container (host ingress / container egress) had extremely low (48-100KB/s) and very inconsistent throughput. As we increased the bandwidth limit, the problem became worse.

To remove the packet loss that kills the container egress performance, we needed to move from ingress policing to egress traffic shaping. We did this by creating an [IFB] device for each warden container in the host namespace. When bandwidth limits are set, traffic from the container that comes into the host side veth interface is redirected to the IFB device. Egress traffic shaping policies are then applied on the IFB device to actually limit the container's egress bandwidth.

With the shaping on on the IFB, we saw consistent behavior and throughput for container ingress and egress.

[IFB]: http://www.linuxfoundation.org/collaborate/workgroups/networking/ifb

**Comment by Amit-PivotalLabs** [comment]
Have you tested that this works with a large number of instances on a runner, in a long-lived environment?  I don't have many specific concerns, but with a change like this that I and our team have little expertise on, I'm just being cautious.  One specific concern would be ensuring the IFB devices are properly garbage-collected.

Also looks like there's potentially some additional code cleanup possible in features/net.rb
* `container_id` is no longer being used in `do_info`, to the registry lookup can be deleted probably
* also in `do_info`, it's looping over a hash where the keys are not being used (and weren't even being used in the prior code), so it could iterate over an array instead of a hash.  Or better, instead of iterating over something, one could extract a small function or lambda and just call it twice with the right arguments
* because there is no more `OUTREG`, the code can directly refer to the `INREG` constant rather than `v[:reg]`.

**Comment by sykesm** [comment]
> Have you tested that this works with a large number of instances on a runner, in a long-lived environment?

I, personally, have not.

> One specific concern would be ensuring the IFB devices are properly garbage-collected.

The devices are explicitly deleted out of container destruction along with the cgroup namespaces. There is no implicit garbage collection as there is with the veth pairs.

> Also looks like there's potentially some additional code cleanup possible in features/net.rb

There are *lots* of things in warden that could use cleanup; it's a code base that hasn't received any attention since the middle of last year. I will update net.rb's do_info to remove the dead code but I would like to refrain from increasing the scope beyond that.

**Comment by sykesm** [comment]
Removed dead code from `do_info` and added an explicit test to verify destruction of host side network interfaces as one did not previously exist.

**Comment by Amit-PivotalLabs** [comment]
Thanks, prioritizing.

**Pull request merged**
